### PR TITLE
Rossa - Add songs from YouTube and "public device" mode

### PR DESCRIPTION
**Pull request by rossadamsonofficial**
Here are a bunch of changes and new features I've been working on, for your consideration. Mostly, it allows users to add songs from youtube, and includes a "public device" mode so that users who don't want to use their phone can use a public computer to register/sign-in/queue songs.

### CODE REVIEW

**Comment by rossadamsonofficial** [comment]
Add song from YouTube screenshots:

Screen Shot 2021-08-23 at 11 40 58 AM

Screen Shot 2021-08-23 at 11 41 47 AM

Screen Shot 2021-08-23 at 11 42 25 AM

**Comment by bhj** [comment]
Hey, really nice work! Would you be able to join the Discord? There's a dev channel where I think we could hash out this kind of feature. Thanks!

**Comment by rossadamsonofficial** [comment]
Thank you! Yes, I'll join the Discord.

**Comment by bhj** [comment]
Thanks again @rizzlesauce - this is a solid contribution, and the public device mode is cool too. Closing isn't something taken lightly.

For future readers: This project used to have built-in YT channel support, but I've come to believe direct YT support is problematic. We did however discuss the possibility of a plug-in system, and I'm 100% behind that!

**Pull request closed without merging**
