### PR TITLE
YouTube search and automatic karaoke mix creation

### PR DESCRIPTION
**Pull request by gazugafan**
This replaces PR #34 (I'm moving the feature to a different branch)

Original description...

I went a little nuts the past few months and added the ability to search for songs on YouTube. You can search for pre-made karaoke mixes 🥱💤, but the really crazy part... you can search for normal songs or music videos and have them automatically turned into karaoke mixes in the background while other songs are being sang 🤯

Here's a video demonstrating the new features...
https://youtu.be/zWa8k6degVs

I understand if you don't want to merge this in. It's a lot of new code to maintain, and it maybe might possibly potentially draw some... unwanted attention. It also might run slightly contrary to some of your stated project goals (like easy setup and not requiring an Internet connection). But, it's also really easy to disable (it is by default), and probably easy enough to completely strip out if necessary.

Hope you give it a look and consideration!

### CODE REVIEW

**Comment by Yetangitu** [comment]
WRT downloaded Youtube clips I notice that these are saved in a temporary directory in a folder with the YT ID containing a single file named `karaoke.mp4`:
```
tmp/1a2b3c4d5e6/karaoke.mp4
```
I'm tempted to change this to a permanent directory (which is added to the _Media Folders_ list) using the same folder name but a 'traditional' `artist - title.mp4` naming scheme...

```
youtube/1a2b3c4d5e6/artist - title.mp4
```
...so that YT-derived files are available as normal search results (maybe with a YT label to identify them as such) the next time around, saving a few clicks and the need for internet access.

Did you have a specific reason for not storing these songs for posterity which would thwart this plan?

**Comment by gazugafan** [comment]
I approached this as temporary storage, so that once a video is removed from all queues the associated files would be deleted and not continually take up more and more space over time. The idea was that you wouldn't want/need to store them forever, because downloading/processing a song only takes a few minutes while other songs are being sung. That does require an active Internet connection and beefy server, though, so I think your idea has merit!

I don't see why it wouldn't work :)

**Comment by gazugafan** [comment]
Oh, also... BHJ has decided not to merge this in. So probably best to raise issues related to this over in [my fork](https://github.com/gazugafan/karaoke-forever). I'm just leaving the PR open for the sake of discoverability ;)

**Comment by bhj** [comment]
Once again, great work and attention to detail. I like @Yetangitu's idea as well.

For future readers: This project used to have built-in YT channel support, but I've come to believe direct YT support is problematic. We did however discuss the possibility of a plug-in system, and I'm 100% behind that!

**Comment by gazugafan** [comment]
I'll keep an eye out for the plugin system and try to port the work over to that if possible! Until then, if anyone is here and looking for the YouTube features, they're in my fork...
https://github.com/gazugafan/karaoke-forever

... which I'm sure is now missing features from the main branch. Wow, even the name of the project has changed! I haven't been singing much karaoke lately, so my fork is falling behind. I find it feature-complete for my purposes, though, so it will probably stay that way 🤷.

**Comment by agittins** [comment]
This is astounding work on all fronts!

@gazugafan I've taken an initial look at rebasing your fork from bhj's tree, but I've got very little frontend experience so I don't know if I might be out of my depth - ultimately I'm hoping to take your setup and create a docker deployment for it, which is a bit more in my wheelhouse.

I'm looking at all the merge conflicts in `package.json` and `package-lock.json` and I'm thinking about how much grief I am going to get myself into! 😅 I'm going to take a crack at the method explained at https://gist.github.com/szemate/6fb69c8e3d8cce3efa9a6c922b337d98 but any pointers would be appreciated (and happy to take discussion elsewhere if more appropriate).

**Comment by gazugafan** [comment]
Cool @agittins! I know some folks have been hoping the fork would get current with the main Karaoke Eternal branch. I just haven't been using this lately, so haven't really had much reason to update it.

The method to merge package-lock.json in that article makes sense to me. It's mostly package.json that you need to worry about. package-lock.json is automatically generated after you do ```npm install```. It basically holds the version numbers of the packages listed in package.json that are *actually* installed--not just the version numbers "recommended" in package.json.

You might consider using the main branch in my fork instead of the youtube branch. That will include all of the youtube stuff, plus options to NOT require username and/or password when creating new accounts, and Case INsensitive usernames. Unless those extra features are already part of the main KE branch now? I haven't checked in awhile.

And yeah, a docker container would be awesome 😁

**Comment by bhj** [comment]
Time to close this one out, but for future readers, there've been some really good discussions in Discord on how to support 3rd-party song sources.

Right now I'm leaning toward a "provider" arrangement (for lack of a better word) where other apps can expose a minimal conforming API that supports querying, downloading, and getting the status of songs being processed. If you're a dev and want to help out, join the Discord and let's talk!

I know it's disappointing to not have this built-in; it was very painful to rip out the initial YT support in the first place. But I really believe keeping these moving parts at arm's length is important for the future of the project, both legally and technically. Thanks to everyone for their understanding.

**Pull request closed without merging**
